In [1]:
from sklearn import preprocessing

In [4]:
le = preprocessing.LabelEncoder()
le.fit([1,2,3,4,66,7,66,2,3,2,7])

LabelEncoder()

In [5]:
le.classes_

array([ 1,  2,  3,  4,  7, 66])

le.transform([1,2,3,66,7,666])

In [7]:
le.transform([1,2,3,66,7])

array([0, 1, 2, 5, 4])

In [8]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

In [10]:
enc.fit([[0,0,3],[1,2,3],[2,3,1],[0,3,2]])

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [11]:
enc.n_values_

array([3, 4, 4])